[package]
name = "libbolt"
version = "0.1.0"
authors = ["J. Ayo Akinyele <ayo@yeletech.org>"]
description = "library for Blind Off-chain Lightweight Transactions (BOLT)"
keywords = ["zcash", "payment channels", "bolt"]
readme = "README.md"
homepage = "https://github.com/yeletech/libbolt"
repository = "https://github.com/yeletech/libbolt"
license = "MIT License"

[dependencies]
bn = { git = "https://github.com/jakinyele/bn", branch= "master" }
rand = "~0.3.14"
bincode = "0.6.1"
sodiumoxide = "0.0.16"
serde = "1.0"
serde_derive = "1.0"
time = "*"
rustc-serialize = "0.3"
secp256k1 = { version = "0.9.2", features = ["rand"] }

[dev-dependencies.bincode]
version = "~0.6.0"
default-features = false
features = ["rustc-serialize"]

[[bin]]
name = "bolt"
path = "bin/bolt.rs"
